module.exports = {
    // Invalid category patterns (regex strings)
    invalidPatterns: [
        "^[\\d,\\.\\s]+֏.*", // Price tags (e.g. "900 ֏")
        "^\\s*\\d+\\s*$", // Just numbers (with potential whitespace)
        "price tag",
        "unknown category",
    ],

    // Heuristic rules for unification
    // Key: Unified Category Name (English)
    // Value: Array of keywords (lower case) to match in translated name
    rules: {
        "Meat, Poultry & Seafood": [
            "meat",
            "poultry",
            "beef",
            "pork",
            "chicken",
            "lamb",
            "veal",
            "fish",
            "seafood",
            "caviar",
            "shrimp",
            "sausage",
            "ham",
            "bacon",
            "steaks",
            "barbecue",
        ],
        "Dairy & Eggs": [
            "dairy",
            "milk",
            "cheese",
            "yogurt",
            "cream",
            "butter",
            "margarine",
            "egg",
            "curd",
            "kefir",
            "matsun",
            "tan",
            "sour cream",
            "condensed milk",
            "ice cream",
            "milkshake",
        ],
        "Fruits & Vegetables": [
            "fruit",
            "vegetable",
            "berry",
            "citrus",
            "apple",
            "banana",
            "tomato",
            "cucumber",
            "potato",
            "onion",
            "carrot",
            "greens",
            "herb",
            "mushroom",
            "dried fruit",
            "nut",
        ],
        "Bakery & Bread": [
            "bread",
            "bakery",
            "pastry",
            "cake",
            "cookie",
            "biscuit",
            "dough",
            "lavash",
            "bun",
            "croissant",
            "sandwich",
            "toast",
            "cracker",
            "wafer",
        ],
        Beverages: [
            "drink",
            "beverage",
            "juice",
            "water",
            "soda",
            "lemonade",
            "tea",
            "coffee",
            "cocoa",
            "syrup",
            "energy drink",
        ],
        Alcohol: [
            "wine",
            "beer",
            "vodka",
            "brandy",
            "cognac",
            "whiskey",
            "tequila",
            "gin",
            "rum",
            "liqueur",
            "champagne",
            "spirit",
            "alcohol",
        ],
        "Snacks & Sweets": [
            "snack",
            "chip",
            "crisp",
            "popcorn",
            "chocolate",
            "candy",
            "sweet",
            "gum",
            "jelly",
            "marmalade",
            "marshmallow",
            "bar",
            "halva",
            "nougat",
            "dessert",
        ],
        "Grocery & Pantry": [
            "grocery",
            "pantry",
            "canned",
            "oil",
            "sauce",
            "spice",
            "condiment",
            "pasta",
            "rice",
            "grain",
            "cereal",
            "flour",
            "sugar",
            "salt",
            "honey",
            "jam",
            "spread",
            "pickle",
            "olive",
            "vinegar",
            "ketchup",
            "mayonnaise",
            "mustard",
        ],
        "Frozen Foods": ["frozen", "dumpling", "ravioli", "khinkali"],
        Baby: ["baby", "infant", "toddler", "diaper", "wipe", "formula"],
        "Personal Care & Hygiene": [
            "personal care",
            "hygiene",
            "soap",
            "shampoo",
            "shower",
            "tooth",
            "oral",
            "shave",
            "razor",
            "deodorant",
            "sanitary",
            "tissue",
            "cotton",
            "mask",
            "cream",
            "lotion",
            "cosmetic",
            "makeup",
            "perfume",
        ],
        "Household & Cleaning": [
            "household",
            "cleaning",
            "detergent",
            "laundry",
            "dishwashing",
            "bleach",
            "cleaner",
            "paper towel",
            "toilet paper",
            "sponge",
            "garbage bag",
            "foil",
            "napkin",
        ],
        "Pet Supplies": ["pet", "cat", "dog", "animal", "bird", "fish food"],
        "Home & Kitchen": [
            "kitchen",
            "cookware",
            "tableware",
            "glassware",
            "textile",
            "bedding",
            "towel",
            "storage",
            "organizer",
            "decor",
            "candle",
            "party",
            "stationery",
            "office",
            "toy",
            "game",
        ],
        Tobacco: ["tobacco", "cigarette", "cigar", "lighter"],
    },

    getUnifiedCategory: function (translatedName) {
        if (!translatedName) return "Other";
        const text = String(translatedName);

        // Word-boundary match so "ham" doesn't hit "hamar", "bar" doesn't hit "barometer" etc.
        for (const [unified, keywords] of Object.entries(this.rules)) {
            for (const k of keywords) {
                const escaped = k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
                const re = new RegExp(`\\b${escaped}\\b|\\b${escaped}s\\b`, "i"); // allow simple plural
                if (re.test(text)) return unified;
            }
        }

        return "Other";
    },

    isValidCategory: function (name) {
        if (!name) return false;
        const lower = name.toLowerCase();
        for (const pattern of this.invalidPatterns) {
            if (new RegExp(pattern).test(lower)) return false;
        }
        return true;
    },
};
